name: Docker Kodi Headless

description: |
  Docker containers for Kodi with multiple display server options and VAAPI hardware acceleration.
  
  Available versions:
  - **X11**: More stable and reliable with better Docker support
  - **Wayland**: Modern display server with Weston compositor
  
  Features:
  - VAAPI hardware acceleration for video decoding
  - NVIDIA GPU support via nvidia-docker
  - Hardware-accelerated video playback
  - Web interface for remote control

category: container

topics:
  - kodi
  - docker
  - wayland
  - x11
  - vaapi
  - hardware-acceleration
  - media-center
  - home-theater

supported_platforms:
  - linux/amd64

installation: |
  ## Quick Start
  
  ### X11 Version (Recommended - More Stable)
  ```bash
  # Pull X11 image
  docker pull ghcr.io/bpawnzZ/docker-kodi-headless-x11:latest
  
  # Run X11 version
  docker run -d --name kodi-x11 --privileged \\
    -v /dev/dri:/dev/dri \\
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \\
    -p 8080:8080 \\
    -p 9090:9090 \\
    ghcr.io/bpawnzZ/docker-kodi-headless-x11:latest
  ```

  ### Wayland Version
  ```bash
  # Pull Wayland image
  docker pull ghcr.io/bpawnzZ/docker-kodi-headless-wayland:latest
  
  # Run Wayland version
  docker run -d --name kodi-wayland --privileged \\
    -v /dev/dri:/dev/dri \\
    -p 8080:8080 \\
    -p 9090:9090 \\
    ghcr.io/bpawnzZ/docker-kodi-headless-wayland:latest
  ```

  For more details, see the [README-wayland.md](README-wayland.md) file.