version: '3.8'

services:
  kodi-x11:
    image: ghcr.io/bpawnzz/docker-kodi-headless-wayland:latest
    build:
      context: .
      dockerfile: Dockerfile.x11
    container_name: kodi-x11
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - DISPLAY=:0
    volumes:
      - ./config:/config
      - /dev/dri:/dev/dri
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: unless-stopped

  # NVIDIA GPU support (uncomment if you have NVIDIA GPU)
  # kodi-x11-nvidia:
  #   image: ghcr.io/bpawnzz/docker-kodi-headless-wayland:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.x11
  #   container_name: kodi-x11-nvidia
  #   runtime: nvidia
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=UTC
  #     - DISPLAY=:0
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - NVIDIA_DRIVER_CAPABILITIES=all
  #   volumes:
  #     - ./config:/config
  #     - /dev/dri:/dev/dri
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #   ports:
  #     - "8081:8080"
  #     - "9091:9090"
  #   restart: unless-stopped
