#!/usr/bin/with-contenv bash

# Start Weston Wayland compositor in background
s6-setuidgid abc weston --backend=headless-backend.so &

# Wait for Wayland display to be ready
sleep 2

# Launch Kodi with Wayland
s6-setuidgid abc \
	/usr/bin/kodi --windowing=wayland
