#!/usr/bin/with-contenv bash

# Start X11 server in background
s6-setuidgid abc Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile /tmp/xorg.log -config /tmp/xorg.conf :0 &

# Wait for X11 to be ready
sleep 3

# Launch Kodi with X11
s6-setuidgid abc \
	/usr/bin/kodi